// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmtTj2cBsqZme6rFkc2EBLgmwYQEEsk1c',
    appId: '1:520949532595:web:79d3a08f303291384eedc6',
    messagingSenderId: '520949532595',
    projectId: 'mynotes-first-project-ibuild',
    authDomain: 'mynotes-first-project-ibuild.firebaseapp.com',
    storageBucket: 'mynotes-first-project-ibuild.appspot.com',
    measurementId: 'G-ZKKX2JC16Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYqQRWniBExkLfMRw7IxX1CmcGurwfq9Y',
    appId: '1:520949532595:android:fa5adae0148a0b024eedc6',
    messagingSenderId: '520949532595',
    projectId: 'mynotes-first-project-ibuild',
    storageBucket: 'mynotes-first-project-ibuild.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADO9TkO_t__1NThvJcJzGbs_dC8k9nr_0',
    appId: '1:520949532595:ios:034b6edc82b69e1d4eedc6',
    messagingSenderId: '520949532595',
    projectId: 'mynotes-first-project-ibuild',
    storageBucket: 'mynotes-first-project-ibuild.appspot.com',
    iosClientId:
        '520949532595-qolhvo99cg6initkdhm2t63pckfl72ol.apps.googleusercontent.com',
    iosBundleId: 'com.ibuilddev.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADO9TkO_t__1NThvJcJzGbs_dC8k9nr_0',
    appId: '1:520949532595:ios:034b6edc82b69e1d4eedc6',
    messagingSenderId: '520949532595',
    projectId: 'mynotes-first-project-ibuild',
    storageBucket: 'mynotes-first-project-ibuild.appspot.com',
    iosClientId:
        '520949532595-qolhvo99cg6initkdhm2t63pckfl72ol.apps.googleusercontent.com',
    iosBundleId: 'com.ibuilddev.mynotes',
  );
}
